export function mergeWithDefaultKeywords(keywords = []) {
  return Array.from(new Set([...keywords, ...DEFAULT_META_KEYWORDS])).join(",");
}

const DEFAULT_META_KEYWORDS = [
  "Sahil Rana",
  "Sahil Singh Rana",
  "React.js Developer",
  "Node.js Engineer",
  "Software Engineer",
  "Full Stack Developer",
  "JavaScript Programmer",
  "HTML and CSS Expert",
  "Java Developer",
  "MERN Stack Specialist",
  "Webmyne Software Solutions",
  "Panamax Technologies",
  "Mobifin Applications",
  "GitHub Portfolio",
  "Frontend Development",
  "Backend Development",
  "Innovative Software Solutions",
];

export const resourcesPageKeywords = [
  "Moon Resources",
  "Fascinating Moon Facts",
  "Moon Exploration",
  "Lunar Maria",
  "Interesting Moon Information",
  "Moon Science Resources",
  "Lunar Geography",
  "Space Facts",
  "Astronomy Resources",
  "Moon Phases",
  "Lunar Surface Features",
  "Moon Research Articles",
];

export const homePageKeywords = [
  "Sahil Rana",
  "React js",
  "Node js",
  "Software",
  "SahilSingh",
  "SahilSingh Rana",
  "Experience",
  "Software developer",
  "Programmer",
  "Sahil Singh Rana",
  "Software",
  "Engineer",
  "Developer",
  "Mobifin",
  "Football",
  "Contact",
  "Sahil Rana Software Developer",
  "React.js Developer",
  "Node.js Engineer",
  "Full Stack Developer",
  "MERN Stack Specialist",
  "Sahil Singh Rana Portfolio",
  "JavaScript Programmer",
  "HTML & CSS Expert",
  "Java Developer",
  "Web Development Professional",
  "Software Engineering Experience",
  "Tech Insights and Projects",
  "Contact Sahil Rana",
  "Software Development Projects",
  "Webmyne Solutions Developer",
  "Panamax Software Engineer",
  "Mobifin Application Developer",
  "Programming Skills Showcase",
];

export const contactPageKeyWords = [
  "Sahil Rana",
  "Contact Me",
  "Get in Touch",
  "Portfolio Inquiry",
  "Feedback and Suggestions",
  "Collaboration Opportunities",
  "Business Opportunities",
  "Sahil Singh Rana Contact",
  "Email Me",
  "Email Address",
  "Instagram Profile",
  "Twitter Profile",
  "X Profile",
  "Reach Out",
  "Connect with Me",
  "Professional Contact",
];

export const projectsPageKeywords = [
  "Sahil Rana",
  "Software Development Projects",
  "Portfolio of Projects",
  "Coding and Programming",
  "Web Development Projects",
  "Innovative Software Solutions",
  "Creative Coding Projects",
  "ESP8266 Projects",
  "ESP32 Applications",
  "Tic Tac Toe Game",
  "Music Player Application",
  "Dizi Player App",
  "Real-Time Chat Application",
  "Full Stack Development",
  "IoT Projects with ESP",
];

export const aboutPageKeywords = [
  "Sahil Rana Software Developer",
  "About Sahil Rana",
  "Software Development Journey",
  "Learning and Growth",
  "Professional Experience",
  "Insights into Software Engineering",
  "Passion for Coding",
  "Career Aspirations",
  "Web Development Expertise",
  "Sahil Singh Rana",
  "Software Engineer Profile",
  "Innovative Software Solutions",
  "Tech Enthusiast",
  "Collaboration Opportunities",
  "Football Fanatic",
  "Hire Sahil Rana",
];

export const blogPageKeywords = [
  "Sahil Rana Blog",
  "Sahil Rana",
  "Coding Journey",
  "Poems and Stories",
  "Creative Writing",
  "Technology Insights",
  "JavaScript Tips",
  "Programming Tutorials",
  "Tech Snippets",
  "Web Development Blog",
  "Learn to Code",
  "Software Development",
  "Innovative Projects",
  "Personal Growth in Tech",
  "Tech and Creativity",
];

export const snippetsPageKeywords = [
  "Sahil Rana",
  "JavaScript Code Snippets",
  "Software Developer Snippets",
  "Coding Snippets Collection",
  "Tech Gists",
  "Programming Examples",
  "JavaScript Tips and Tricks",
  "Web Development Snippets",
  "Code Examples",
  "Learn JavaScript",
  "Tech Tutorials",
  "Quick Coding Solutions",
  "Reusable Code Snippets",
  "JavaScript Functions",
  "Sahil Rana Programming",
];

export const postsPageKeywords = [
  "Sahil Rana",
  "Sahil Rana Blog Posts",
  "Software Developer Insights",
  "Technology Articles",
  "Technical Blog Posts",
  "Coding Tutorials",
  "Programming Tips",
  "Web Development Insights",
  "JavaScript Coding",
  "Latest Tech Trends",
  "Software Development Journey",
  "Tech Innovations",
  "Creative Coding Solutions",
  "Learning Programming",
  "Sahil Rana Portfolio",
];
