export function mergeWithDefaultKeywords(keywords = []) {
  return Array.from(new Set([...keywords, ...DEFAULT_META_KEYWORDS])).join(",");
}

const DEFAULT_META_KEYWORDS = [
  "Sahil Rana",
  "React.js",
  "Node.js",
  "Software",
  "Engineer",
  "Developer",
  "Sahil",
  "Singh",
  "Rana",
  "Programmer",
  "Javascript",
  "html",
  "css",
  "java",
  "Sahil Rana",
  "Sahil Singh Rana",
  "SahilSingh",
  "Webmyne",
  "Panamax",
  "Mobifin",
  "Sahil Singh Rana",
];

export const homePageKeywords = [
  "React.js",
  "Node.js",
  "Software",
  "Engineer",
  "Developer",
  "Sahil",
  "SahilSingh",
  "SahilSingh Rana",
  "Experience",
  "Experience",
  "Insights",
  "Software developer",
  "Singh",
  "About",
  "Rana",
  "Programmer",
  "Javascript",
  "html",
  "css",
  "java",
  "Sahil Rana",
  "Sahil Singh Rana",
  "Software",
  "Engineer",
  "Developer",
  "Webmyne",
  "Panamax",
  "Mobifin",
  "Football",
  "Contact",
  "Feedback",
];

export const contactPageKeyWords = [
  "Sahil Rana",
  "Contact",
  "Portfolio",
  "Feedback",
  "Inquiry",
  "Collaboration",
  "Opportunities",
  "Sahil Singh Rana",
  "Email",
  "E mail",
  "instagram",
  "Twitter",
  "X",
];

export const projectsPageKeywords = [
  "Sahil Rana",
  "Projects",
  "Portfolio",
  "Software development",
  "Coding projects",
  "Programming",
  "Web development",
  "Innovation",
  "Creativity",
  "Esp8266",
  "Esp32",
  "tic tac toe",
  "music player",
  "dizi player",
  "chat application",
];

export const aboutPageKeywords = [
  "Sahil Rana",
  "Software developer",
  "Coding journey",
  "Learning",
  "Growth",
  "Aspirations",
  "Experience",
  "Insights",
  "Passion",
  "Development career",
  "About",
  "About Sahil Rana",
  "Sahil",
  "Rana",
  "Singh",
  "Software",
  "Engineer",
  "Developer",
  "Webmyne",
  "Panamax",
  "Mobifin",
  "Football",
  "Hire",
];

export const blogPageKeywords = [
  "Blog",
  "Sahil Rana",
  "Sahil",
  "poems",
  "story",
  "poem",
  "Technology",
  "Javacript",
  "Write",
  "Tech",
  "snippets",
  "Code",
  "learn",
];

export const snippetsPageKeywords = [
  "Sahil Rana",
  "Software developer",
  "Code snippets",
  "code",
  "Snippets",
  "Gists",
  "List",
  "Tech",
  "Technology",
  "Javascript",
];

export const postsPageKeywords = [
  "Sahil Rana",
  "Software developer",
  "Blog posts",
  "List",
  "Technology",
  "Technical",
  "posts",
  "Coding",
];
