function normalizeExact(str) {
  return str.toLowerCase().replace(/\s+/g, " ").trim();
}

export function mergeWithDefaultKeywords(keywords = []) {
  const merged = [...keywords, ...DEFAULT_META_KEYWORDS];
  const seen = new Set();
  const unique = [];

  for (const kw of merged) {
    const norm = normalizeExact(kw);
    if (!seen.has(norm)) {
      seen.add(norm);
      unique.push(kw);
    }
  }

  return unique.join(",");
}

const DEFAULT_META_KEYWORDS = [
  "Sahil Rana",
  "Sahil Singh Rana",
  "Full Stack Developer",
  "MERN Stack Developer",
  "React.js Developer",
  "Node.js Developer",
  "JavaScript Developer",
  "Frontend Developer",
  "Backend Developer",
  "Web Developer Portfolio",
  "Software Engineer",
  "JavaScript Programmer",
  "HTML CSS Expert",
  "Java Developer",
  "Webmyne Software Solutions",
  "Panamax Technologies",
  "Mobifin Applications",
  "GitHub Projects",
  "Innovative Software Development",
  "Modern Web Applications",
];

export const resourcesPageKeywords = [
  "Moon Facts for Kids",
  "Interesting Moon Facts",
  "Moon Formation Facts",
  "Moon Phases Explained",
  "Moon Distance from Earth",
  "How Far is the Moon",
  "Moon Surface Features",
  "Lunar Maria Facts",
  "Moonquakes Explained",
  "Water on the Moon",
  "Moon Geology Resources",
  "Credible Moon Fact Sources",
  "Lunar Science Facts",
  "Astronomy Moon Resources",
  "Moon Exploration Facts",
  "Lunar Research Articles",
  "Moon Facts With Sources",
];

export const homePageKeywords = [
  "Sahil Rana",
  "Sahil Singh Rana",
  "Sahil Singh Portfolio",
  "Full Stack Developer",
  "MERN Stack Developer",
  "React.js Developer",
  "Node.js Developer",
  "JavaScript Developer",
  "Frontend Developer",
  "Backend Developer",
  "Software Engineer",
  "Web Developer Portfolio",
  "Java Developer",
  "HTML CSS Expert",
  "Programming Projects",
  "Software Development Experience",
  "Web Development Professional",
  "GitHub Projects",
  "Webmyne Software Solutions",
  "Panamax Technologies",
  "Mobifin Applications",
  "Sahil Rana Software Developer",
  "Software Development Projects",
  "Tech Insights and Tutorials",
  "Hire Full Stack Developer",
  "Modern Web Applications",
  "Innovative Software Development",
];

export const contactPageKeyWords = [
  "Sahil Rana Contact",
  "Sahil Singh Rana Contact",
  "Contact Sahil Rana",
  "Get in Touch with Sahil Rana",
  "Work with Full Stack Developer",
  "Collaboration with Software Developer",
  "Business Opportunities with Sahil Rana",
  "Hire React.js Developer Sahil Rana",
  "Hire Node.js Developer Sahil Rana",
  "Connect with Sahil Singh Rana",
  "Professional Contact Sahil Rana",
  "Reach Sahil Rana for Projects",
  "Web Development Collaboration",
  "Software Development Consultation",
  "Full Stack Developer Portfolio Contact",
];

export const projectsPageKeywords = [
  "Sahil Rana Projects",
  "Sahil Singh Rana Portfolio",
  "Software Development Projects by Sahil Rana",
  "Full Stack Development Projects",
  "Web Development Portfolio Sahil Rana",
  "JavaScript Projects Portfolio",
  "React.js and Node.js Projects",
  "MERN Stack Development Projects",
  "ESP8266 IoT Projects",
  "ESP32 IoT Applications",
  "IoT Development Portfolio",
  "Tic Tac Toe Game in JavaScript",
  "Music Player Web Application",
  "Dizi Player App Project",
  "Real-Time Chat Application Project",
  "Innovative Software Solutions Portfolio",
  "Personal Coding Projects by Sahil Rana",
  "Open Source Projects Sahil Rana",
  "Programming Portfolio Showcase",
];

export const aboutPageKeywords = [
  "About Sahil Rana Software Developer",
  "Sahil Singh Rana Profile",
  "Full Stack Developer Biography",
  "Software Engineering Journey Sahil Rana",
  "React.js and Node.js Developer Story",
  "MERN Stack Developer Experience",
  "Professional Software Engineer Sahil Rana",
  "Career Background of Sahil Rana",
  "Web Development Expertise and Skills",
  "Programming Journey of Sahil Rana",
  "Hire Sahil Rana Software Engineer",
  "Software Development Insights",
  "Tech Enthusiast and Innovator",
  "Personal Interests of Sahil Rana",
  "Football Fan and Coder",
  "Collaboration with Sahil Rana",
  "Innovative Software Solutions Career",
  "Sahil Rana Professional Experience",
  "Meet Sahil Singh Rana",
];

export const blogPageKeywords = [
  "Sahil Rana Blog",
  "Sahil Singh Rana Articles",
  "Coding Journey and Experiences",
  "React.js Tutorials by Sahil Rana",
  "Node.js Guides and Insights",
  "JavaScript Tips and Best Practices",
  "Web Development Blog Posts",
  "MERN Stack Learning Resources",
  "Software Engineering Tutorials",
  "Full Stack Development Blog",
  "Creative Writing by Sahil Rana",
  "Poems and Short Stories",
  "Technology Insights and Trends",
  "Programming Knowledge Sharing",
  "Learn to Code with Sahil Rana",
  "Personal Growth in Tech Industry",
  "Developer Tips and Tech Snippets",
  "Sahil Rana Programming Blog",
];

export const snippetsPageKeywords = [
  "Sahil Rana Code Snippets",
  "JavaScript Code Snippets Collection",
  "Reusable JavaScript Functions",
  "Web Development Snippets by Sahil Rana",
  "Quick Coding Solutions",
  "Programming Code Examples",
  "Frontend Development Snippets",
  "Backend Development Snippets",
  "React.js Snippets and Tips",
  "Node.js Snippets and Solutions",
  "MERN Stack Code Snippets",
  "JavaScript Tips and Tricks",
  "Learn JavaScript Snippets",
  "Developer Snippets Library",
  "Sahil Rana Programming Snippets",
];

export const postsPageKeywords = [
  "Sahil Rana Blog Posts",
  "Technical Articles by Sahil Rana",
  "Software Developer Blog Insights",
  "Latest Programming Tutorials",
  "Web Development Articles",
  "JavaScript Development Posts",
  "Full Stack Developer Blog",
  "In-Depth Coding Tutorials",
  "React.js and Node.js Blog Posts",
  "Practical Programming Tips",
  "Cutting Edge Tech Articles",
  "Software Engineering Insights",
  "Innovative Coding Solutions",
  "Developer Learning Resources",
  "Sahil Rana Tech Portfolio Blog",
];

export const curlToolPageKeyWords = [
  "curl command generator",
  "online curl generator",
  "generate curl command",
  "curl command builder",
  "curl builder online",
  "create curl from request",
  "curl request generator",
  "curl command from http request",
  "bash curl generator",
  "curl command maker",
  "curl flags generator",
  "curl headers generator",
  "generate curl with headers",
  "convert request to curl",
  "postman to curl generator",
  "http request to curl",
  "api testing curl generator",
  "curl command for api",
  "curl examples generator",
  "curl with bearer token",
  "curl basic auth generator",
  "curl multipart form generator",
  "curl json payload generator",
  "curl file upload generator",
  "download curl command",
  "shareable curl command",
  "curl command formatter",
  "curl command syntax highlighter",
  "curl command with cookies",
  "curl command for developers",
  "curl CLI generator",
  "developer tool curl generator",
  "online http client curl",
  "curl command from fetch",
  "curl snippets generator",
  "curl automation tool",
  "generate curl for webhook",
  "curl command playground",
  "curl playground online",
];
