// Texture resolution constants live at module scope so they are visible alongside
// the worker call and can be adjusted without hunting inside the init() body.
// These must match the size values expected by the worker (e.g. texture-worker.js).
const TEX_SIZE = 630; // Resolution of the diffuse and bump textures (square).
const ROUGH_SIZE = 490; // Resolution of the roughness texture (square, can be lower).

export class Moon {
  constructor(scene, onComplete) {
    this.scene = scene;
    this.mesh = null;

    // Private refs kept for dispose() — Three.js requires explicit disposal of GPU
    // resources (textures, materials, geometries) because the JS garbage collector
    // cannot free WebGL objects held by the GPU driver.
    this._geometry = null;
    this._material = null;

    this.init(onComplete);
  }

  async init(onComplete) {
    const THREE = await import("three");

    const worker = new Worker(new URL("./texture-worker.js", import.meta.url), {
      type: "module",
    });

    // If the worker throws (malformed message, JS error inside the worker, etc.),
    // onmessage never fires and onComplete is never called — the scene silently stays
    // empty with no feedback. onerror surfaces that failure so the caller can react.
    worker.onerror = (err) => {
      console.error("Texture worker failed:", err);
      worker.terminate();
    };

    worker.onmessage = (e) => {
      const diffuseTex = new THREE.DataTexture(
        new Uint8Array(e.data.diffuse),
        TEX_SIZE,
        TEX_SIZE,
        THREE.RGBAFormat,
      );

      // SRGBColorSpace tells Three.js to gamma-correct the diffuse colors when
      // sampling, matching how monitor displays expect color data to be encoded.
      // Bump and roughness maps are linear data (height/roughness values, not color),
      // so they must NOT have SRGBColorSpace applied.
      diffuseTex.colorSpace = THREE.SRGBColorSpace;

      // TEX_SIZE (630) and ROUGH_SIZE (490) are not powers of two.
      // For NPOT textures, mipmaps cannot be hardware-generated by older WebGL drivers.
      // Three.js WebGL2 renderer handles NPOT fine, but setting generateMipmaps = false
      // and minFilter = LinearFilter makes the intent explicit and avoids any renderer
      // warnings about unsupported mipmap generation for non-power-of-two dimensions.
      diffuseTex.generateMipmaps = false;
      diffuseTex.minFilter = THREE.LinearFilter;
      diffuseTex.needsUpdate = true;

      const bumpTex = new THREE.DataTexture(
        new Uint8Array(e.data.bump),
        TEX_SIZE,
        TEX_SIZE,
        THREE.RGBAFormat,
      );
      bumpTex.generateMipmaps = false;
      bumpTex.minFilter = THREE.LinearFilter;
      bumpTex.needsUpdate = true;

      const roughTex = new THREE.DataTexture(
        new Uint8Array(e.data.rough),
        ROUGH_SIZE,
        ROUGH_SIZE,
        THREE.RGBAFormat,
      );
      roughTex.generateMipmaps = false;
      roughTex.minFilter = THREE.LinearFilter;
      roughTex.needsUpdate = true;

      this._material = new THREE.MeshStandardMaterial({
        map: diffuseTex,
        bumpMap: bumpTex,
        bumpScale: 0.045,
        roughnessMap: roughTex,
        roughness: 0.92,
      });

      // 60×60 segments gives a smooth silhouette without excessive vertex count.
      // Lower (e.g. 32): visible faceting on the edge of the sphere.
      // Higher (e.g. 128): diminishing visual return with quadratic vertex cost.
      const radius = 0.4;
      this._geometry = new THREE.SphereGeometry(radius, 60, 60);
      this.mesh = new THREE.Mesh(this._geometry, this._material);

      // castShadow / receiveShadow have no effect unless renderer.shadowMap.enabled
      // is set to true. They are kept here as an explicit opt-in flag so enabling
      // shadow maps in the future automatically picks up the moon without extra changes.
      this.mesh.castShadow = true;
      this.mesh.receiveShadow = true;

      this.scene.add(this.mesh);

      worker.terminate();
      if (onComplete) onComplete();
    };

    worker.postMessage({ size: TEX_SIZE, roughSize: ROUGH_SIZE });
  }

  // Releases all GPU-side resources owned by this Moon instance.
  // Must be called before removing the Moon from the scene to avoid WebGL memory leaks,
  // because Three.js does not garbage-collect GPU objects automatically.
  dispose() {
    if (!this.mesh) return;

    this.scene.remove(this.mesh);

    // Each texture is an independent GPU upload — each must be disposed individually.
    this._material?.map?.dispose();
    this._material?.bumpMap?.dispose();
    this._material?.roughnessMap?.dispose();
    this._material?.dispose();
    this._geometry?.dispose();

    this.mesh = null;
    this._geometry = null;
    this._material = null;
  }

  setVisibility(visible) {
    if (this.mesh) this.mesh.visible = visible;
  }
}
