name: Refresh Spotify Top Items

on:
  schedule:
    - cron: "25 17 * * 0-6"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-spotify-data:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Get Spotify Token
        id: get-token
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        run: |
          echo "import requests, base64, os" > get_token.py
          echo "try:" >> get_token.py
          echo "    CLIENT_ID = os.environ['SPOTIFY_CLIENT_ID']" >> get_token.py
          echo "    CLIENT_SECRET = os.environ['SPOTIFY_CLIENT_SECRET']" >> get_token.py
          echo "    auth_url = 'https://accounts.spotify.com/api/token'" >> get_token.py
          echo "    auth_header = {'Authorization': 'Basic ' + base64.b64encode(f'{CLIENT_ID}:{CLIENT_SECRET}'.encode()).decode()}" >> get_token.py
          echo "    auth_data = {'grant_type': 'client_credentials'}" >> get_token.py
          echo "    response = requests.post(auth_url, headers=auth_header, data=auth_data)" >> get_token.py
          echo "    response.raise_for_status()" >> get_token.py
          echo "    access_token = response.json()['access_token']" >> get_token.py
          echo "    print(f'::set-output name=access_token::{access_token}')" >> get_token.py
          echo "except Exception as e:" >> get_token.py
          echo "    print(f'Error getting Spotify token: {str(e)}')" >> get_token.py
          echo "    exit(1)" >> get_token.py
          python get_token.py

      - name: Fetch Top Artists and Songs
        id: fetch-data
        env:
          ACCESS_TOKEN: ${{ steps.get-token.outputs.access_token }}
        run: |
          echo "import requests, json, os" > fetch_data.py
          echo "try:" >> fetch_data.py
          echo "    access_token = os.environ['ACCESS_TOKEN']" >> fetch_data.py
          echo "    headers = {'Authorization': f'Bearer {access_token}', 'Content-Type': 'application/json'}" >> fetch_data.py
          echo "    top_artists_url = 'https://api.spotify.com/v1/me/top/artists'" >> fetch_data.py
          echo "    top_tracks_url = 'https://api.spotify.com/v1/me/top/tracks'" >> fetch_data.py
          echo "    artists_response = requests.get(top_artists_url, headers=headers)" >> fetch_data.py
          echo "    tracks_response = requests.get(top_tracks_url, headers=headers)" >> fetch_data.py
          echo "    artists_response.raise_for_status()" >> fetch_data.py
          echo "    tracks_response.raise_for_status()" >> fetch_data.py
          echo "    top_artists = artists_response.json()" >> fetch_data.py
          echo "    top_tracks = tracks_response.json()" >> fetch_data.py
          echo "    spotify_data = {'top_artists': top_artists, 'top_tracks': top_tracks}" >> fetch_data.py
          echo "    with open('public/spotifyData.json', 'w') as f:" >> fetch_data.py
          echo "        json.dump(spotify_data, f, indent=2)" >> fetch_data.py
          echo "except Exception as e:" >> fetch_data.py
          echo "    print(f'Error fetching Spotify data: {str(e)}')" >> fetch_data.py
          echo "    exit(1)" >> fetch_data.py
          python fetch_data.py

      - name: Commit and Push Spotify Data
        run: |
          git config --global user.name 'Sahil Singh Rana'
          git config --global user.email 'ranasahil98@gmail.com'
          git add public/spotifyData.json
          git commit -m 'Update Spotify Data'
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
